### ISSUE TITLE
Postscript生成错误

### ISSUE THREAD

**Issue by bctnry** [Coq-zh/SF-zh#4]
https://github.com/Coq-zh/SF-zh/blob/ca0b95b23de7ea58d6dc99803aa1b65653d0e4b1/lf-current/Postscript.html#L168

从这一行开始。

**Comment by liyishuai** [comment]
Also observed in the [English version](https://softwarefoundations.cis.upenn.edu/lf-current/Postscript.html#lab377). The maintainers are aware of this issue and will fix it soon. Thanks!

**Comment by liyishuai** [comment]
Fixed in ddccec738046490db5d333e497b362f2f3f8266e

**Comment by bctnry** [comment]
no. this is not fully fixed.
https://github.com/Coq-zh/SF-zh/blob/ddccec738046490db5d333e497b362f2f3f8266e/lf-current/Postscript.html#L187

**Comment by liyishuai** [comment]
Will be fixed in r30. Thanks!
P.S. Now I know what "invalid" label means. I should have used "bug".
